// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using WebHealth.Infrastructure.Persistence;
using WebHealth.Infrastructure.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
