// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Auditing;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AuditEventEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Auditing.AuditEvent",
                typeof(AuditEvent),
                baseEntityType,
                propertyCount: 12,
                foreignKeyCount: 1,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AuditEvent).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var action = runtimeEntityType.AddProperty(
                "Action",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("Action", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<Action>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            action.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            action.AddAnnotation("Relational:ColumnName", "action");

            var actorIdentifier = runtimeEntityType.AddProperty(
                "ActorIdentifier",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("ActorIdentifier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<ActorIdentifier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36);
            actorIdentifier.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            actorIdentifier.AddAnnotation("Relational:ColumnName", "actor_identifier");

            var actorUserId = runtimeEntityType.AddProperty(
                "ActorUserId",
                typeof(Guid?),
                propertyInfo: typeof(AuditEvent).GetProperty("ActorUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<ActorUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            actorUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            actorUserId.AddAnnotation("Relational:ColumnName", "actor_user_id");

            var afterValues = runtimeEntityType.AddProperty(
                "AfterValues",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("AfterValues", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<AfterValues>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            afterValues.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            afterValues.AddAnnotation("Relational:ColumnName", "after_values");
            afterValues.AddAnnotation("Relational:ColumnType", "jsonb");

            var beforeValues = runtimeEntityType.AddProperty(
                "BeforeValues",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("BeforeValues", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<BeforeValues>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            beforeValues.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            beforeValues.AddAnnotation("Relational:ColumnName", "before_values");
            beforeValues.AddAnnotation("Relational:ColumnType", "jsonb");

            var correlationId = runtimeEntityType.AddProperty(
                "CorrelationId",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("CorrelationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<CorrelationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 128);
            correlationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            correlationId.AddAnnotation("Relational:ColumnName", "correlation_id");

            var entityIdentifier = runtimeEntityType.AddProperty(
                "EntityIdentifier",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("EntityIdentifier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<EntityIdentifier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2048);
            entityIdentifier.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            entityIdentifier.AddAnnotation("Relational:ColumnName", "entity_identifier");

            var entityType = runtimeEntityType.AddProperty(
                "EntityType",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("EntityType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<EntityType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            entityType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            entityType.AddAnnotation("Relational:ColumnName", "entity_type");

            var occurredAt = runtimeEntityType.AddProperty(
                "OccurredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(AuditEvent).GetProperty("OccurredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<OccurredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            occurredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            occurredAt.AddAnnotation("Relational:ColumnName", "occurred_at");
            occurredAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var outcome = runtimeEntityType.AddProperty(
                "Outcome",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("Outcome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<Outcome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            outcome.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            outcome.AddAnnotation("Relational:ColumnName", "outcome");

            var requestMethod = runtimeEntityType.AddProperty(
                "RequestMethod",
                typeof(string),
                propertyInfo: typeof(AuditEvent).GetProperty("RequestMethod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEvent).GetField("<RequestMethod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 16);
            requestMethod.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            requestMethod.AddAnnotation("Relational:ColumnName", "request_method");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_audit_event");

            var index = runtimeEntityType.AddIndex(
                new[] { occurredAt });
            index.AddAnnotation("Relational:Name", "ix_audit_event_occurred_at");

            var index0 = runtimeEntityType.AddIndex(
                new[] { action, occurredAt });
            index0.AddAnnotation("Relational:Name", "ix_audit_event_action_occurred_at");

            var index1 = runtimeEntityType.AddIndex(
                new[] { actorUserId, occurredAt });
            index1.AddAnnotation("Relational:Name", "ix_audit_event_actor_user_id_occurred_at");

            var index2 = runtimeEntityType.AddIndex(
                new[] { entityType, entityIdentifier, occurredAt });
            index2.AddAnnotation("Relational:Name", "ix_audit_event_entity_type_entity_identifier_occurred_at");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ActorUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_audit_event_app_user_actor_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "audit_event");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
