// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CheckConfigurationSnapshotEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.CheckConfigurationSnapshot",
                typeof(CheckConfigurationSnapshot),
                baseEntityType,
                propertyCount: 21,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var logicalCheckId = runtimeEntityType.AddProperty(
                "LogicalCheckId",
                typeof(Guid),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("LogicalCheckId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<LogicalCheckId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            logicalCheckId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            logicalCheckId.AddAnnotation("Relational:ColumnName", "logical_check_id");

            var acceptedStatusCodes = runtimeEntityType.AddProperty(
                "AcceptedStatusCodes",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("AcceptedStatusCodes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<AcceptedStatusCodes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            acceptedStatusCodes.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            acceptedStatusCodes.AddAnnotation("Relational:ColumnName", "accepted_status_codes");

            var configurationFingerprint = runtimeEntityType.AddProperty(
                "ConfigurationFingerprint",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("ConfigurationFingerprint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<ConfigurationFingerprint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            configurationFingerprint.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            configurationFingerprint.AddAnnotation("Relational:ColumnName", "configuration_fingerprint");

            var confirmationSource = runtimeEntityType.AddProperty(
                "ConfirmationSource",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("ConfirmationSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<ConfirmationSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            confirmationSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            confirmationSource.AddAnnotation("Relational:ColumnName", "confirmation_source");

            var contentMarkerComparison = runtimeEntityType.AddProperty(
                "ContentMarkerComparison",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("ContentMarkerComparison", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<ContentMarkerComparison>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            contentMarkerComparison.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            contentMarkerComparison.AddAnnotation("Relational:ColumnName", "content_marker_comparison");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var criticalThresholdMs = runtimeEntityType.AddProperty(
                "CriticalThresholdMs",
                typeof(int?),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("CriticalThresholdMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<CriticalThresholdMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            criticalThresholdMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            criticalThresholdMs.AddAnnotation("Relational:ColumnName", "critical_threshold_ms");

            var failureConfirmationCount = runtimeEntityType.AddProperty(
                "FailureConfirmationCount",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("FailureConfirmationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<FailureConfirmationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            failureConfirmationCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            failureConfirmationCount.AddAnnotation("Relational:ColumnName", "failure_confirmation_count");

            var intervalSeconds = runtimeEntityType.AddProperty(
                "IntervalSeconds",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("IntervalSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<IntervalSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            intervalSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            intervalSeconds.AddAnnotation("Relational:ColumnName", "interval_seconds");

            var intervalSource = runtimeEntityType.AddProperty(
                "IntervalSource",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("IntervalSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<IntervalSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            intervalSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            intervalSource.AddAnnotation("Relational:ColumnName", "interval_source");

            var maxRedirects = runtimeEntityType.AddProperty(
                "MaxRedirects",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("MaxRedirects", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<MaxRedirects>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxRedirects.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxRedirects.AddAnnotation("Relational:ColumnName", "max_redirects");

            var maxResponseBodyBytes = runtimeEntityType.AddProperty(
                "MaxResponseBodyBytes",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("MaxResponseBodyBytes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<MaxResponseBodyBytes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxResponseBodyBytes.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxResponseBodyBytes.AddAnnotation("Relational:ColumnName", "max_response_body_bytes");

            var monitorType = runtimeEntityType.AddProperty(
                "MonitorType",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("MonitorType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<MonitorType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            monitorType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            monitorType.AddAnnotation("Relational:ColumnName", "monitor_type");

            var productionHttpSeverity = runtimeEntityType.AddProperty(
                "ProductionHttpSeverity",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("ProductionHttpSeverity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<ProductionHttpSeverity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            productionHttpSeverity.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            productionHttpSeverity.AddAnnotation("Relational:ColumnName", "production_http_severity");

            var recoveryConfirmationCount = runtimeEntityType.AddProperty(
                "RecoveryConfirmationCount",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("RecoveryConfirmationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<RecoveryConfirmationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            recoveryConfirmationCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recoveryConfirmationCount.AddAnnotation("Relational:ColumnName", "recovery_confirmation_count");

            var requiredContentMarker = runtimeEntityType.AddProperty(
                "RequiredContentMarker",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("RequiredContentMarker", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<RequiredContentMarker>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            requiredContentMarker.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            requiredContentMarker.AddAnnotation("Relational:ColumnName", "required_content_marker");

            var schemaVersion = runtimeEntityType.AddProperty(
                "SchemaVersion",
                typeof(short),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("SchemaVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<SchemaVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (short)0);
            schemaVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            schemaVersion.AddAnnotation("Relational:ColumnName", "schema_version");

            var thresholdSource = runtimeEntityType.AddProperty(
                "ThresholdSource",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("ThresholdSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<ThresholdSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            thresholdSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            thresholdSource.AddAnnotation("Relational:ColumnName", "threshold_source");

            var timeoutSeconds = runtimeEntityType.AddProperty(
                "TimeoutSeconds",
                typeof(int),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("TimeoutSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<TimeoutSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            timeoutSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timeoutSeconds.AddAnnotation("Relational:ColumnName", "timeout_seconds");

            var timeoutSource = runtimeEntityType.AddProperty(
                "TimeoutSource",
                typeof(string),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("TimeoutSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<TimeoutSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            timeoutSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timeoutSource.AddAnnotation("Relational:ColumnName", "timeout_source");

            var warningThresholdMs = runtimeEntityType.AddProperty(
                "WarningThresholdMs",
                typeof(int?),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("WarningThresholdMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<WarningThresholdMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            warningThresholdMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            warningThresholdMs.AddAnnotation("Relational:ColumnName", "warning_threshold_ms");

            var key = runtimeEntityType.AddKey(
                new[] { logicalCheckId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_check_configuration_snapshot");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("LogicalCheckId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                unique: true,
                required: true,
                requiredDependent: true);

            var logicalCheck = declaringEntityType.AddNavigation("LogicalCheck",
                runtimeForeignKey,
                onDependent: true,
                typeof(LogicalCheck),
                propertyInfo: typeof(CheckConfigurationSnapshot).GetProperty("LogicalCheck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckConfigurationSnapshot).GetField("<LogicalCheck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var configurationSnapshot = principalEntityType.AddNavigation("ConfigurationSnapshot",
                runtimeForeignKey,
                onDependent: false,
                typeof(CheckConfigurationSnapshot),
                propertyInfo: typeof(LogicalCheck).GetProperty("ConfigurationSnapshot", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LogicalCheck).GetField("<ConfigurationSnapshot>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_check_configuration_snapshot_logical_check_logical_check_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "check_configuration_snapshot");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
