// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Maintenance;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CheckResultEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.CheckResult",
                typeof(CheckResult),
                baseEntityType,
                propertyCount: 21,
                navigationCount: 4,
                foreignKeyCount: 2,
                unnamedIndexCount: 4,
                keyCount: 1);

            var logicalCheckId = runtimeEntityType.AddProperty(
                "LogicalCheckId",
                typeof(Guid),
                propertyInfo: typeof(CheckResult).GetProperty("LogicalCheckId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<LogicalCheckId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            logicalCheckId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            logicalCheckId.AddAnnotation("Relational:ColumnName", "logical_check_id");

            var completedAt = runtimeEntityType.AddProperty(
                "CompletedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CheckResult).GetProperty("CompletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<CompletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            completedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            completedAt.AddAnnotation("Relational:ColumnName", "completed_at");
            completedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var connectDurationMs = runtimeEntityType.AddProperty(
                "ConnectDurationMs",
                typeof(int?),
                propertyInfo: typeof(CheckResult).GetProperty("ConnectDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<ConnectDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            connectDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            connectDurationMs.AddAnnotation("Relational:ColumnName", "connect_duration_ms");

            var countsForUptime = runtimeEntityType.AddProperty(
                "CountsForUptime",
                typeof(bool),
                propertyInfo: typeof(CheckResult).GetProperty("CountsForUptime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<CountsForUptime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            countsForUptime.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            countsForUptime.AddAnnotation("Relational:ColumnName", "counts_for_uptime");

            var decodedLength = runtimeEntityType.AddProperty(
                "DecodedLength",
                typeof(long?),
                propertyInfo: typeof(CheckResult).GetProperty("DecodedLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<DecodedLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            decodedLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            decodedLength.AddAnnotation("Relational:ColumnName", "decoded_length");

            var dnsDurationMs = runtimeEntityType.AddProperty(
                "DnsDurationMs",
                typeof(int?),
                propertyInfo: typeof(CheckResult).GetProperty("DnsDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<DnsDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dnsDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            dnsDurationMs.AddAnnotation("Relational:ColumnName", "dns_duration_ms");

            var endpointMonitorId = runtimeEntityType.AddProperty(
                "EndpointMonitorId",
                typeof(Guid),
                propertyInfo: typeof(CheckResult).GetProperty("EndpointMonitorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<EndpointMonitorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointMonitorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointMonitorId.AddAnnotation("Relational:ColumnName", "endpoint_monitor_id");

            var failureCategory = runtimeEntityType.AddProperty(
                "FailureCategory",
                typeof(string),
                propertyInfo: typeof(CheckResult).GetProperty("FailureCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<FailureCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            failureCategory.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            failureCategory.AddAnnotation("Relational:ColumnName", "failure_category");

            var httpStatus = runtimeEntityType.AddProperty(
                "HttpStatus",
                typeof(int?),
                propertyInfo: typeof(CheckResult).GetProperty("HttpStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<HttpStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            httpStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            httpStatus.AddAnnotation("Relational:ColumnName", "http_status");

            var isMaintenance = runtimeEntityType.AddProperty(
                "IsMaintenance",
                typeof(bool),
                propertyInfo: typeof(CheckResult).GetProperty("IsMaintenance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<IsMaintenance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isMaintenance.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isMaintenance.AddAnnotation("Relational:ColumnName", "is_maintenance");

            var lengthSource = runtimeEntityType.AddProperty(
                "LengthSource",
                typeof(string),
                propertyInfo: typeof(CheckResult).GetProperty("LengthSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<LengthSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 30);
            lengthSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lengthSource.AddAnnotation("Relational:ColumnName", "length_source");

            var maintenanceOccurrenceId = runtimeEntityType.AddProperty(
                "MaintenanceOccurrenceId",
                typeof(Guid?),
                propertyInfo: typeof(CheckResult).GetProperty("MaintenanceOccurrenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<MaintenanceOccurrenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            maintenanceOccurrenceId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maintenanceOccurrenceId.AddAnnotation("Relational:ColumnName", "maintenance_occurrence_id");

            var measuredAt = runtimeEntityType.AddProperty(
                "MeasuredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CheckResult).GetProperty("MeasuredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<MeasuredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            measuredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            measuredAt.AddAnnotation("Relational:ColumnName", "measured_at");
            measuredAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var monitorSource = runtimeEntityType.AddProperty(
                "MonitorSource",
                typeof(string),
                propertyInfo: typeof(CheckResult).GetProperty("MonitorSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<MonitorSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            monitorSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            monitorSource.AddAnnotation("Relational:ColumnName", "monitor_source");

            var outcome = runtimeEntityType.AddProperty(
                "Outcome",
                typeof(string),
                propertyInfo: typeof(CheckResult).GetProperty("Outcome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<Outcome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            outcome.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            outcome.AddAnnotation("Relational:ColumnName", "outcome");

            var responseTruncated = runtimeEntityType.AddProperty(
                "ResponseTruncated",
                typeof(bool),
                propertyInfo: typeof(CheckResult).GetProperty("ResponseTruncated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<ResponseTruncated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            responseTruncated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            responseTruncated.AddAnnotation("Relational:ColumnName", "response_truncated");

            var safeDiagnostic = runtimeEntityType.AddProperty(
                "SafeDiagnostic",
                typeof(string),
                propertyInfo: typeof(CheckResult).GetProperty("SafeDiagnostic", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<SafeDiagnostic>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            safeDiagnostic.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            safeDiagnostic.AddAnnotation("Relational:ColumnName", "safe_diagnostic");

            var tlsDurationMs = runtimeEntityType.AddProperty(
                "TlsDurationMs",
                typeof(int?),
                propertyInfo: typeof(CheckResult).GetProperty("TlsDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<TlsDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tlsDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            tlsDurationMs.AddAnnotation("Relational:ColumnName", "tls_duration_ms");

            var totalDurationMs = runtimeEntityType.AddProperty(
                "TotalDurationMs",
                typeof(int),
                propertyInfo: typeof(CheckResult).GetProperty("TotalDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<TotalDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            totalDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            totalDurationMs.AddAnnotation("Relational:ColumnName", "total_duration_ms");

            var transferredLength = runtimeEntityType.AddProperty(
                "TransferredLength",
                typeof(long?),
                propertyInfo: typeof(CheckResult).GetProperty("TransferredLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<TransferredLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            transferredLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            transferredLength.AddAnnotation("Relational:ColumnName", "transferred_length");

            var ttfbDurationMs = runtimeEntityType.AddProperty(
                "TtfbDurationMs",
                typeof(int?),
                propertyInfo: typeof(CheckResult).GetProperty("TtfbDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<TtfbDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ttfbDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            ttfbDurationMs.AddAnnotation("Relational:ColumnName", "ttfb_duration_ms");

            var key = runtimeEntityType.AddKey(
                new[] { logicalCheckId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_check_result");

            var index = runtimeEntityType.AddIndex(
                new[] { maintenanceOccurrenceId });
            index.AddAnnotation("Relational:Name", "ix_check_result_maintenance_occurrence_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { endpointMonitorId, measuredAt });
            index0.AddAnnotation("Relational:Name", "ix_check_result_monitor_measured_at");

            var index1 = runtimeEntityType.AddIndex(
                new[] { logicalCheckId, endpointMonitorId },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ix_check_result_logical_check_id_endpoint_monitor_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { measuredAt, logicalCheckId });
            index2.AddAnnotation("Relational:Name", "ix_check_result_measured_at_logical_check_id");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MaintenanceOccurrenceId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            var maintenanceOccurrence = declaringEntityType.AddNavigation("MaintenanceOccurrence",
                runtimeForeignKey,
                onDependent: true,
                typeof(MaintenanceOccurrence),
                propertyInfo: typeof(CheckResult).GetProperty("MaintenanceOccurrence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<MaintenanceOccurrence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_check_result_maintenance_occurrence_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("LogicalCheckId"), declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id"), principalEntityType.FindProperty("EndpointMonitorId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                unique: true,
                required: true);

            var logicalCheck = declaringEntityType.AddNavigation("LogicalCheck",
                runtimeForeignKey,
                onDependent: true,
                typeof(LogicalCheck),
                propertyInfo: typeof(CheckResult).GetProperty("LogicalCheck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<LogicalCheck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var result = principalEntityType.AddNavigation("Result",
                runtimeForeignKey,
                onDependent: false,
                typeof(CheckResult),
                propertyInfo: typeof(LogicalCheck).GetProperty("Result", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LogicalCheck).GetField("<Result>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_check_result_logical_check_monitor");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "check_result");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
