// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Crawling;
using WebHealth.Infrastructure.Registry;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CrawlRunEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Crawling.CrawlRun",
                typeof(CrawlRun),
                baseEntityType,
                propertyCount: 18,
                navigationCount: 2,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(CrawlRun).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var allowedHosts = runtimeEntityType.AddProperty(
                "AllowedHosts",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("AllowedHosts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<AllowedHosts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4096);
            allowedHosts.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            allowedHosts.AddAnnotation("Relational:ColumnName", "allowed_hosts");

            var allowedPathPrefixes = runtimeEntityType.AddProperty(
                "AllowedPathPrefixes",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("AllowedPathPrefixes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<AllowedPathPrefixes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4096);
            allowedPathPrefixes.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            allowedPathPrefixes.AddAnnotation("Relational:ColumnName", "allowed_path_prefixes");

            var checkExternalLinks = runtimeEntityType.AddProperty(
                "CheckExternalLinks",
                typeof(bool),
                propertyInfo: typeof(CrawlRun).GetProperty("CheckExternalLinks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<CheckExternalLinks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            checkExternalLinks.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            checkExternalLinks.AddAnnotation("Relational:ColumnName", "check_external_links");

            var endpointId = runtimeEntityType.AddProperty(
                "EndpointId",
                typeof(Guid),
                propertyInfo: typeof(CrawlRun).GetProperty("EndpointId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<EndpointId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointId.AddAnnotation("Relational:ColumnName", "endpoint_id");

            var failureReason = runtimeEntityType.AddProperty(
                "FailureReason",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("FailureReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<FailureReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);
            failureReason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            failureReason.AddAnnotation("Relational:ColumnName", "failure_reason");

            var finishedAt = runtimeEntityType.AddProperty(
                "FinishedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(CrawlRun).GetProperty("FinishedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<FinishedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            finishedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            finishedAt.AddAnnotation("Relational:ColumnName", "finished_at");
            finishedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var linksRecorded = runtimeEntityType.AddProperty(
                "LinksRecorded",
                typeof(int),
                propertyInfo: typeof(CrawlRun).GetProperty("LinksRecorded", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<LinksRecorded>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            linksRecorded.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            linksRecorded.AddAnnotation("Relational:ColumnName", "links_recorded");

            var maxDepth = runtimeEntityType.AddProperty(
                "MaxDepth",
                typeof(int),
                propertyInfo: typeof(CrawlRun).GetProperty("MaxDepth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<MaxDepth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxDepth.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxDepth.AddAnnotation("Relational:ColumnName", "max_depth");

            var maxPages = runtimeEntityType.AddProperty(
                "MaxPages",
                typeof(int),
                propertyInfo: typeof(CrawlRun).GetProperty("MaxPages", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<MaxPages>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxPages.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxPages.AddAnnotation("Relational:ColumnName", "max_pages");

            var pagesFetched = runtimeEntityType.AddProperty(
                "PagesFetched",
                typeof(int),
                propertyInfo: typeof(CrawlRun).GetProperty("PagesFetched", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<PagesFetched>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            pagesFetched.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            pagesFetched.AddAnnotation("Relational:ColumnName", "pages_fetched");

            var queryPolicy = runtimeEntityType.AddProperty(
                "QueryPolicy",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("QueryPolicy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<QueryPolicy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            queryPolicy.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            queryPolicy.AddAnnotation("Relational:ColumnName", "query_policy");

            var robotsOverrideGranted = runtimeEntityType.AddProperty(
                "RobotsOverrideGranted",
                typeof(bool),
                propertyInfo: typeof(CrawlRun).GetProperty("RobotsOverrideGranted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<RobotsOverrideGranted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            robotsOverrideGranted.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            robotsOverrideGranted.AddAnnotation("Relational:ColumnName", "robots_override_granted");

            var robotsOverrideRefusedBecause = runtimeEntityType.AddProperty(
                "RobotsOverrideRefusedBecause",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("RobotsOverrideRefusedBecause", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<RobotsOverrideRefusedBecause>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            robotsOverrideRefusedBecause.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            robotsOverrideRefusedBecause.AddAnnotation("Relational:ColumnName", "robots_override_refused_because");

            var seedUrls = runtimeEntityType.AddProperty(
                "SeedUrls",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("SeedUrls", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<SeedUrls>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8192);
            seedUrls.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            seedUrls.AddAnnotation("Relational:ColumnName", "seed_urls");

            var startedAt = runtimeEntityType.AddProperty(
                "StartedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CrawlRun).GetProperty("StartedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<StartedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            startedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            startedAt.AddAnnotation("Relational:ColumnName", "started_at");
            startedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:ColumnName", "status");

            var stopReason = runtimeEntityType.AddProperty(
                "StopReason",
                typeof(string),
                propertyInfo: typeof(CrawlRun).GetProperty("StopReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<StopReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            stopReason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            stopReason.AddAnnotation("Relational:ColumnName", "stop_reason");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_crawl_run");

            var index = runtimeEntityType.AddIndex(
                new[] { endpointId, startedAt });
            index.AddAnnotation("Relational:Name", "ix_crawl_run_endpoint_id_started_at");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var endpoint = declaringEntityType.AddNavigation("Endpoint",
                runtimeForeignKey,
                onDependent: true,
                typeof(Endpoint),
                propertyInfo: typeof(CrawlRun).GetProperty("Endpoint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CrawlRun).GetField("<Endpoint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_crawl_run_endpoint_endpoint_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "crawl_run");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
