// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Health;
using WebHealth.Infrastructure.Monitoring;
using WebHealth.Infrastructure.Registry;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class EndpointHealthEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Health.EndpointHealth",
                typeof(EndpointHealth),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var endpointMonitorId = runtimeEntityType.AddProperty(
                "EndpointMonitorId",
                typeof(Guid),
                propertyInfo: typeof(EndpointHealth).GetProperty("EndpointMonitorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<EndpointMonitorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointMonitorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointMonitorId.AddAnnotation("Relational:ColumnName", "endpoint_monitor_id");

            var confirmedAt = runtimeEntityType.AddProperty(
                "ConfirmedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EndpointHealth).GetProperty("ConfirmedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<ConfirmedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            confirmedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            confirmedAt.AddAnnotation("Relational:ColumnName", "confirmed_at");
            confirmedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var confirmedStatus = runtimeEntityType.AddProperty(
                "ConfirmedStatus",
                typeof(string),
                propertyInfo: typeof(EndpointHealth).GetProperty("ConfirmedStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<ConfirmedStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            confirmedStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            confirmedStatus.AddAnnotation("Relational:ColumnName", "confirmed_status");

            var evidenceLogicalCheckId = runtimeEntityType.AddProperty(
                "EvidenceLogicalCheckId",
                typeof(Guid?),
                propertyInfo: typeof(EndpointHealth).GetProperty("EvidenceLogicalCheckId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<EvidenceLogicalCheckId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            evidenceLogicalCheckId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            evidenceLogicalCheckId.AddAnnotation("Relational:ColumnName", "evidence_logical_check_id");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(EndpointHealth).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            version.AddAnnotation("Relational:ColumnName", "version");

            var key = runtimeEntityType.AddKey(
                new[] { endpointMonitorId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_endpoint_health");

            var index = runtimeEntityType.AddIndex(
                new[] { evidenceLogicalCheckId, endpointMonitorId });
            index.AddAnnotation("Relational:Name", "ix_endpoint_health_evidence_check_monitor");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                unique: true,
                required: true);

            var endpointMonitor = declaringEntityType.AddNavigation("EndpointMonitor",
                runtimeForeignKey,
                onDependent: true,
                typeof(EndpointMonitor),
                propertyInfo: typeof(EndpointHealth).GetProperty("EndpointMonitor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<EndpointMonitor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var endpointHealth = principalEntityType.AddNavigation("EndpointHealth",
                runtimeForeignKey,
                onDependent: false,
                typeof(EndpointHealth),
                propertyInfo: typeof(EndpointMonitor).GetProperty("EndpointHealth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<EndpointHealth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_health_endpoint_monitor_endpoint_monitor_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EvidenceLogicalCheckId"), declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id"), principalEntityType.FindProperty("EndpointMonitorId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            var evidenceLogicalCheck = declaringEntityType.AddNavigation("EvidenceLogicalCheck",
                runtimeForeignKey,
                onDependent: true,
                typeof(LogicalCheck),
                propertyInfo: typeof(EndpointHealth).GetProperty("EvidenceLogicalCheck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointHealth).GetField("<EvidenceLogicalCheck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_health_logical_check_monitor");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "endpoint_health");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
