// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Registry;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class EndpointMonitorEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Registry.EndpointMonitor",
                typeof(EndpointMonitor),
                baseEntityType,
                propertyCount: 23,
                navigationCount: 5,
                foreignKeyCount: 5,
                unnamedIndexCount: 6,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(EndpointMonitor).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var boundedOverrides = runtimeEntityType.AddProperty(
                "BoundedOverrides",
                typeof(string),
                propertyInfo: typeof(EndpointMonitor).GetProperty("BoundedOverrides", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<BoundedOverrides>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            boundedOverrides.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            boundedOverrides.AddAnnotation("Relational:ColumnName", "bounded_overrides");
            boundedOverrides.AddAnnotation("Relational:ColumnType", "jsonb");

            var configurationFingerprint = runtimeEntityType.AddProperty(
                "ConfigurationFingerprint",
                typeof(string),
                propertyInfo: typeof(EndpointMonitor).GetProperty("ConfigurationFingerprint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<ConfigurationFingerprint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            configurationFingerprint.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            configurationFingerprint.AddAnnotation("Relational:ColumnName", "configuration_fingerprint");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EndpointMonitor).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var createdByUserId = runtimeEntityType.AddProperty(
                "CreatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(EndpointMonitor).GetProperty("CreatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<CreatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            createdByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdByUserId.AddAnnotation("Relational:ColumnName", "created_by_user_id");

            var criticalThresholdMs = runtimeEntityType.AddProperty(
                "CriticalThresholdMs",
                typeof(int?),
                propertyInfo: typeof(EndpointMonitor).GetProperty("CriticalThresholdMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<CriticalThresholdMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            criticalThresholdMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            criticalThresholdMs.AddAnnotation("Relational:ColumnName", "critical_threshold_ms");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(EndpointMonitor).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");
            deletedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var deletedByUserId = runtimeEntityType.AddProperty(
                "DeletedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(EndpointMonitor).GetProperty("DeletedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<DeletedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedByUserId.AddAnnotation("Relational:ColumnName", "deleted_by_user_id");

            var endpointId = runtimeEntityType.AddProperty(
                "EndpointId",
                typeof(Guid),
                propertyInfo: typeof(EndpointMonitor).GetProperty("EndpointId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<EndpointId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointId.AddAnnotation("Relational:ColumnName", "endpoint_id");

            var failureConfirmationCount = runtimeEntityType.AddProperty(
                "FailureConfirmationCount",
                typeof(int),
                propertyInfo: typeof(EndpointMonitor).GetProperty("FailureConfirmationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<FailureConfirmationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            failureConfirmationCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            failureConfirmationCount.AddAnnotation("Relational:ColumnName", "failure_confirmation_count");

            var intervalSeconds = runtimeEntityType.AddProperty(
                "IntervalSeconds",
                typeof(int),
                propertyInfo: typeof(EndpointMonitor).GetProperty("IntervalSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<IntervalSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            intervalSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            intervalSeconds.AddAnnotation("Relational:ColumnName", "interval_seconds");

            var isEnabled = runtimeEntityType.AddProperty(
                "IsEnabled",
                typeof(bool),
                propertyInfo: typeof(EndpointMonitor).GetProperty("IsEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<IsEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isEnabled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isEnabled.AddAnnotation("Relational:ColumnName", "is_enabled");

            var monitorType = runtimeEntityType.AddProperty(
                "MonitorType",
                typeof(string),
                propertyInfo: typeof(EndpointMonitor).GetProperty("MonitorType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<MonitorType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            monitorType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            monitorType.AddAnnotation("Relational:ColumnName", "monitor_type");

            var nextDueAt = runtimeEntityType.AddProperty(
                "NextDueAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EndpointMonitor).GetProperty("NextDueAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<NextDueAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            nextDueAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            nextDueAt.AddAnnotation("Relational:ColumnName", "next_due_at");
            nextDueAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var policyProfileId = runtimeEntityType.AddProperty(
                "PolicyProfileId",
                typeof(Guid),
                propertyInfo: typeof(EndpointMonitor).GetProperty("PolicyProfileId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<PolicyProfileId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            policyProfileId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            policyProfileId.AddAnnotation("Relational:ColumnName", "policy_profile_id");

            var recoveryConfirmationCount = runtimeEntityType.AddProperty(
                "RecoveryConfirmationCount",
                typeof(int),
                propertyInfo: typeof(EndpointMonitor).GetProperty("RecoveryConfirmationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<RecoveryConfirmationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            recoveryConfirmationCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recoveryConfirmationCount.AddAnnotation("Relational:ColumnName", "recovery_confirmation_count");

            var scheduleAnchor = runtimeEntityType.AddProperty(
                "ScheduleAnchor",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EndpointMonitor).GetProperty("ScheduleAnchor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<ScheduleAnchor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            scheduleAnchor.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            scheduleAnchor.AddAnnotation("Relational:ColumnName", "schedule_anchor");
            scheduleAnchor.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var schedulingEnabled = runtimeEntityType.AddProperty(
                "SchedulingEnabled",
                typeof(bool),
                propertyInfo: typeof(EndpointMonitor).GetProperty("SchedulingEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<SchedulingEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: true);
            schedulingEnabled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            schedulingEnabled.AddAnnotation("Relational:ColumnName", "scheduling_enabled");
            schedulingEnabled.AddAnnotation("Relational:DefaultValue", true);

            var timeoutSeconds = runtimeEntityType.AddProperty(
                "TimeoutSeconds",
                typeof(int),
                propertyInfo: typeof(EndpointMonitor).GetProperty("TimeoutSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<TimeoutSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            timeoutSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timeoutSeconds.AddAnnotation("Relational:ColumnName", "timeout_seconds");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EndpointMonitor).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");
            updatedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var updatedByUserId = runtimeEntityType.AddProperty(
                "UpdatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(EndpointMonitor).GetProperty("UpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<UpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            updatedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedByUserId.AddAnnotation("Relational:ColumnName", "updated_by_user_id");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(EndpointMonitor).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            version.AddAnnotation("Relational:ColumnName", "version");

            var warningThresholdMs = runtimeEntityType.AddProperty(
                "WarningThresholdMs",
                typeof(int?),
                propertyInfo: typeof(EndpointMonitor).GetProperty("WarningThresholdMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<WarningThresholdMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            warningThresholdMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            warningThresholdMs.AddAnnotation("Relational:ColumnName", "warning_threshold_ms");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_endpoint_monitor");

            var index = runtimeEntityType.AddIndex(
                new[] { createdByUserId });
            index.AddAnnotation("Relational:Name", "ix_endpoint_monitor_created_by_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { deletedByUserId });
            index0.AddAnnotation("Relational:Name", "ix_endpoint_monitor_deleted_by_user_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { policyProfileId });
            index1.AddAnnotation("Relational:Name", "ix_endpoint_monitor_policy_profile_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { updatedByUserId });
            index2.AddAnnotation("Relational:Name", "ix_endpoint_monitor_updated_by_user_id");

            var index3 = runtimeEntityType.AddIndex(
                new[] { endpointId, monitorType },
                unique: true);
            index3.AddAnnotation("Relational:Filter", "deleted_at IS NULL");
            index3.AddAnnotation("Relational:Name", "ix_endpoint_monitor_endpoint_id_monitor_type");

            var index4 = runtimeEntityType.AddIndex(
                new[] { nextDueAt, id });
            index4.AddAnnotation("Relational:Filter", "deleted_at IS NULL AND is_enabled AND scheduling_enabled");
            index4.AddAnnotation("Relational:Name", "ix_endpoint_monitor_next_due_at_id");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CreatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_monitor_app_user_created_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DeletedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_monitor_app_user_deleted_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var endpoint = declaringEntityType.AddNavigation("Endpoint",
                runtimeForeignKey,
                onDependent: true,
                typeof(Endpoint),
                propertyInfo: typeof(EndpointMonitor).GetProperty("Endpoint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<Endpoint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var monitors = principalEntityType.AddNavigation("Monitors",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<EndpointMonitor>),
                propertyInfo: typeof(Endpoint).GetProperty("Monitors", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Endpoint).GetField("<Monitors>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_monitor_endpoint_endpoint_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PolicyProfileId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var policyProfile = declaringEntityType.AddNavigation("PolicyProfile",
                runtimeForeignKey,
                onDependent: true,
                typeof(PolicyProfile),
                propertyInfo: typeof(EndpointMonitor).GetProperty("PolicyProfile", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EndpointMonitor).GetField("<PolicyProfile>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_monitor_policy_profile_policy_profile_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_endpoint_monitor_app_user_updated_by_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "endpoint_monitor");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
