// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Identity;
using WebHealth.Infrastructure.Incidents;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IncidentEventEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Incidents.IncidentEvent",
                typeof(IncidentEvent),
                baseEntityType,
                propertyCount: 11,
                navigationCount: 2,
                foreignKeyCount: 4,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(IncidentEvent).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var actorUserId = runtimeEntityType.AddProperty(
                "ActorUserId",
                typeof(Guid?),
                propertyInfo: typeof(IncidentEvent).GetProperty("ActorUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<ActorUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            actorUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            actorUserId.AddAnnotation("Relational:ColumnName", "actor_user_id");

            var boundedNote = runtimeEntityType.AddProperty(
                "BoundedNote",
                typeof(string),
                propertyInfo: typeof(IncidentEvent).GetProperty("BoundedNote", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<BoundedNote>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            boundedNote.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            boundedNote.AddAnnotation("Relational:ColumnName", "bounded_note");

            var eventType = runtimeEntityType.AddProperty(
                "EventType",
                typeof(string),
                propertyInfo: typeof(IncidentEvent).GetProperty("EventType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<EventType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            eventType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            eventType.AddAnnotation("Relational:ColumnName", "event_type");

            var fromOwnerSubjectId = runtimeEntityType.AddProperty(
                "FromOwnerSubjectId",
                typeof(Guid?),
                propertyInfo: typeof(IncidentEvent).GetProperty("FromOwnerSubjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<FromOwnerSubjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            fromOwnerSubjectId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            fromOwnerSubjectId.AddAnnotation("Relational:ColumnName", "from_owner_subject_id");

            var fromStatus = runtimeEntityType.AddProperty(
                "FromStatus",
                typeof(string),
                propertyInfo: typeof(IncidentEvent).GetProperty("FromStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<FromStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 30);
            fromStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            fromStatus.AddAnnotation("Relational:ColumnName", "from_status");

            var incidentId = runtimeEntityType.AddProperty(
                "IncidentId",
                typeof(Guid),
                propertyInfo: typeof(IncidentEvent).GetProperty("IncidentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<IncidentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            incidentId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            incidentId.AddAnnotation("Relational:ColumnName", "incident_id");

            var occurredAt = runtimeEntityType.AddProperty(
                "OccurredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(IncidentEvent).GetProperty("OccurredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<OccurredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            occurredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            occurredAt.AddAnnotation("Relational:ColumnName", "occurred_at");
            occurredAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var sequenceNumber = runtimeEntityType.AddProperty(
                "SequenceNumber",
                typeof(long),
                propertyInfo: typeof(IncidentEvent).GetProperty("SequenceNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<SequenceNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sequenceNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sequenceNumber.AddAnnotation("Relational:ColumnName", "sequence_number");

            var toOwnerSubjectId = runtimeEntityType.AddProperty(
                "ToOwnerSubjectId",
                typeof(Guid?),
                propertyInfo: typeof(IncidentEvent).GetProperty("ToOwnerSubjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<ToOwnerSubjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            toOwnerSubjectId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            toOwnerSubjectId.AddAnnotation("Relational:ColumnName", "to_owner_subject_id");

            var toStatus = runtimeEntityType.AddProperty(
                "ToStatus",
                typeof(string),
                propertyInfo: typeof(IncidentEvent).GetProperty("ToStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<ToStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 30);
            toStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            toStatus.AddAnnotation("Relational:ColumnName", "to_status");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_incident_event");

            var index = runtimeEntityType.AddIndex(
                new[] { actorUserId });
            index.AddAnnotation("Relational:Name", "ix_incident_event_actor_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { fromOwnerSubjectId });
            index0.AddAnnotation("Relational:Name", "ix_incident_event_from_owner_subject_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { toOwnerSubjectId });
            index1.AddAnnotation("Relational:Name", "ix_incident_event_to_owner_subject_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { incidentId, sequenceNumber },
                unique: true);
            index2.AddAnnotation("Relational:Name", "ix_incident_event_incident_id_sequence_number");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ActorUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            var actorUser = declaringEntityType.AddNavigation("ActorUser",
                runtimeForeignKey,
                onDependent: true,
                typeof(ApplicationUser),
                propertyInfo: typeof(IncidentEvent).GetProperty("ActorUser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<ActorUser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_incident_event_app_user_actor_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("FromOwnerSubjectId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_incident_event_owner_subject_from_owner_subject_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IncidentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var incident = declaringEntityType.AddNavigation("Incident",
                runtimeForeignKey,
                onDependent: true,
                typeof(Incident),
                propertyInfo: typeof(IncidentEvent).GetProperty("Incident", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IncidentEvent).GetField("<Incident>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var events = principalEntityType.AddNavigation("Events",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<IncidentEvent>),
                propertyInfo: typeof(Incident).GetProperty("Events", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Incident).GetField("<Events>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_incident_event_incident_incident_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ToOwnerSubjectId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_incident_event_owner_subject_to_owner_subject_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "incident_event");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
