// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Maintenance;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MaintenanceWindowEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Maintenance.MaintenanceWindow",
                typeof(MaintenanceWindow),
                baseEntityType,
                propertyCount: 19,
                navigationCount: 2,
                foreignKeyCount: 3,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var continueFailureCounter = runtimeEntityType.AddProperty(
                "ContinueFailureCounter",
                typeof(bool),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("ContinueFailureCounter", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<ContinueFailureCounter>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            continueFailureCounter.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            continueFailureCounter.AddAnnotation("Relational:ColumnName", "continue_failure_counter");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var createdByUserId = runtimeEntityType.AddProperty(
                "CreatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("CreatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<CreatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            createdByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdByUserId.AddAnnotation("Relational:ColumnName", "created_by_user_id");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");
            deletedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var deletedByUserId = runtimeEntityType.AddProperty(
                "DeletedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("DeletedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<DeletedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedByUserId.AddAnnotation("Relational:ColumnName", "deleted_by_user_id");

            var expandedThrough = runtimeEntityType.AddProperty(
                "ExpandedThrough",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("ExpandedThrough", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<ExpandedThrough>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expandedThrough.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            expandedThrough.AddAnnotation("Relational:ColumnName", "expanded_through");
            expandedThrough.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var pauseEscalation = runtimeEntityType.AddProperty(
                "PauseEscalation",
                typeof(bool),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("PauseEscalation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<PauseEscalation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            pauseEscalation.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            pauseEscalation.AddAnnotation("Relational:ColumnName", "pause_escalation");

            var reason = runtimeEntityType.AddProperty(
                "Reason",
                typeof(string),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("Reason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<Reason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            reason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            reason.AddAnnotation("Relational:ColumnName", "reason");

            var recurrenceDaysOfWeek = runtimeEntityType.AddProperty(
                "RecurrenceDaysOfWeek",
                typeof(int),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("RecurrenceDaysOfWeek", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<RecurrenceDaysOfWeek>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            recurrenceDaysOfWeek.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recurrenceDaysOfWeek.AddAnnotation("Relational:ColumnName", "recurrence_days_of_week");

            var recurrencePattern = runtimeEntityType.AddProperty(
                "RecurrencePattern",
                typeof(string),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("RecurrencePattern", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<RecurrencePattern>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                maxLength: 10);
            recurrencePattern.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recurrencePattern.AddAnnotation("Relational:ColumnName", "recurrence_pattern");
            recurrencePattern.AddAnnotation("Relational:DefaultValue", "None");

            var recurrenceUntil = runtimeEntityType.AddProperty(
                "RecurrenceUntil",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("RecurrenceUntil", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<RecurrenceUntil>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recurrenceUntil.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recurrenceUntil.AddAnnotation("Relational:ColumnName", "recurrence_until");
            recurrenceUntil.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var scheduleDurationSeconds = runtimeEntityType.AddProperty(
                "ScheduleDurationSeconds",
                typeof(int),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("ScheduleDurationSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<ScheduleDurationSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            scheduleDurationSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            scheduleDurationSeconds.AddAnnotation("Relational:ColumnName", "schedule_duration_seconds");

            var scheduleStartsAt = runtimeEntityType.AddProperty(
                "ScheduleStartsAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("ScheduleStartsAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<ScheduleStartsAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            scheduleStartsAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            scheduleStartsAt.AddAnnotation("Relational:ColumnName", "schedule_starts_at");
            scheduleStartsAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var suppressionPolicy = runtimeEntityType.AddProperty(
                "SuppressionPolicy",
                typeof(string),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("SuppressionPolicy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<SuppressionPolicy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            suppressionPolicy.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            suppressionPolicy.AddAnnotation("Relational:ColumnName", "suppression_policy");

            var timezoneId = runtimeEntityType.AddProperty(
                "TimezoneId",
                typeof(string),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("TimezoneId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<TimezoneId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            timezoneId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timezoneId.AddAnnotation("Relational:ColumnName", "timezone_id");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");
            updatedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var updatedByUserId = runtimeEntityType.AddProperty(
                "UpdatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("UpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<UpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            updatedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedByUserId.AddAnnotation("Relational:ColumnName", "updated_by_user_id");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            version.AddAnnotation("Relational:ColumnName", "version");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_maintenance_window");

            var index = runtimeEntityType.AddIndex(
                new[] { createdByUserId });
            index.AddAnnotation("Relational:Name", "ix_maintenance_window_created_by_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { deletedAt });
            index0.AddAnnotation("Relational:Name", "ix_maintenance_window_deleted_at");

            var index1 = runtimeEntityType.AddIndex(
                new[] { deletedByUserId });
            index1.AddAnnotation("Relational:Name", "ix_maintenance_window_deleted_by_user_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { updatedByUserId });
            index2.AddAnnotation("Relational:Name", "ix_maintenance_window_updated_by_user_id");

            var index3 = runtimeEntityType.AddIndex(
                new[] { recurrencePattern, expandedThrough });
            index3.AddAnnotation("Relational:Name", "ix_maintenance_window_recurrence_expansion");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CreatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_window_app_user_created_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DeletedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_window_app_user_deleted_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_window_app_user_updated_by_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "maintenance_window");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
