// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Maintenance;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MaintenanceTargetEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Maintenance.MaintenanceTarget",
                typeof(MaintenanceTarget),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                foreignKeyCount: 6,
                unnamedIndexCount: 6,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var clientId = runtimeEntityType.AddProperty(
                "ClientId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("ClientId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<ClientId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            clientId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            clientId.AddAnnotation("Relational:ColumnName", "client_id");

            var endpointId = runtimeEntityType.AddProperty(
                "EndpointId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("EndpointId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<EndpointId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            endpointId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointId.AddAnnotation("Relational:ColumnName", "endpoint_id");

            var endpointMonitorId = runtimeEntityType.AddProperty(
                "EndpointMonitorId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("EndpointMonitorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<EndpointMonitorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            endpointMonitorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointMonitorId.AddAnnotation("Relational:ColumnName", "endpoint_monitor_id");

            var environmentId = runtimeEntityType.AddProperty(
                "EnvironmentId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("EnvironmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<EnvironmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            environmentId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            environmentId.AddAnnotation("Relational:ColumnName", "environment_id");

            var maintenanceWindowId = runtimeEntityType.AddProperty(
                "MaintenanceWindowId",
                typeof(Guid),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("MaintenanceWindowId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<MaintenanceWindowId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            maintenanceWindowId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maintenanceWindowId.AddAnnotation("Relational:ColumnName", "maintenance_window_id");

            var websiteId = runtimeEntityType.AddProperty(
                "WebsiteId",
                typeof(Guid?),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("WebsiteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<WebsiteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            websiteId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            websiteId.AddAnnotation("Relational:ColumnName", "website_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_maintenance_target");

            var index = runtimeEntityType.AddIndex(
                new[] { clientId });
            index.AddAnnotation("Relational:Name", "ix_maintenance_target_client_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { endpointId });
            index0.AddAnnotation("Relational:Name", "ix_maintenance_target_endpoint_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { endpointMonitorId });
            index1.AddAnnotation("Relational:Name", "ix_maintenance_target_endpoint_monitor_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { environmentId });
            index2.AddAnnotation("Relational:Name", "ix_maintenance_target_environment_id");

            var index3 = runtimeEntityType.AddIndex(
                new[] { maintenanceWindowId });
            index3.AddAnnotation("Relational:Name", "ix_maintenance_target_maintenance_window_id");

            var index4 = runtimeEntityType.AddIndex(
                new[] { websiteId });
            index4.AddAnnotation("Relational:Name", "ix_maintenance_target_website_id");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClientId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_client_client_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_endpoint_endpoint_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_endpoint_monitor_endpoint_monitor_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EnvironmentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_environment_environment_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MaintenanceWindowId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var maintenanceWindow = declaringEntityType.AddNavigation("MaintenanceWindow",
                runtimeForeignKey,
                onDependent: true,
                typeof(MaintenanceWindow),
                propertyInfo: typeof(MaintenanceTarget).GetProperty("MaintenanceWindow", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceTarget).GetField("<MaintenanceWindow>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var targets = principalEntityType.AddNavigation("Targets",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<MaintenanceTarget>),
                propertyInfo: typeof(MaintenanceWindow).GetProperty("Targets", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MaintenanceWindow).GetField("<Targets>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_maintenance_window_maintenance_window_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey6(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("WebsiteId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_maintenance_target_website_website_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "maintenance_target");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
