// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MonitoringRuntimeStateEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.MonitoringRuntimeState",
                typeof(MonitoringRuntimeState),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var operation = runtimeEntityType.AddProperty(
                "Operation",
                typeof(string),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("Operation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<Operation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 40);
            operation.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            operation.AddAnnotation("Relational:ColumnName", "operation");

            var consecutiveFailures = runtimeEntityType.AddProperty(
                "ConsecutiveFailures",
                typeof(int),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("ConsecutiveFailures", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<ConsecutiveFailures>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            consecutiveFailures.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            consecutiveFailures.AddAnnotation("Relational:ColumnName", "consecutive_failures");

            var failureCategory = runtimeEntityType.AddProperty(
                "FailureCategory",
                typeof(string),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("FailureCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<FailureCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            failureCategory.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            failureCategory.AddAnnotation("Relational:ColumnName", "failure_category");

            var invocationId = runtimeEntityType.AddProperty(
                "InvocationId",
                typeof(Guid),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("InvocationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<InvocationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            invocationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            invocationId.AddAnnotation("Relational:ColumnName", "invocation_id");

            var lastDurationMs = runtimeEntityType.AddProperty(
                "LastDurationMs",
                typeof(long?),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("LastDurationMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<LastDurationMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastDurationMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lastDurationMs.AddAnnotation("Relational:ColumnName", "last_duration_ms");

            var lastFailedAt = runtimeEntityType.AddProperty(
                "LastFailedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("LastFailedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<LastFailedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastFailedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lastFailedAt.AddAnnotation("Relational:ColumnName", "last_failed_at");
            lastFailedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var lastStartedAt = runtimeEntityType.AddProperty(
                "LastStartedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("LastStartedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<LastStartedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            lastStartedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lastStartedAt.AddAnnotation("Relational:ColumnName", "last_started_at");
            lastStartedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var lastSucceededAt = runtimeEntityType.AddProperty(
                "LastSucceededAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MonitoringRuntimeState).GetProperty("LastSucceededAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringRuntimeState).GetField("<LastSucceededAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastSucceededAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lastSucceededAt.AddAnnotation("Relational:ColumnName", "last_succeeded_at");
            lastSucceededAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var key = runtimeEntityType.AddKey(
                new[] { operation });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_monitoring_runtime_state");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "monitoring_runtime_state");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
