// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MonitoringDailyAggregateEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.MonitoringDailyAggregate",
                typeof(MonitoringDailyAggregate),
                baseEntityType,
                propertyCount: 25,
                foreignKeyCount: 1,
                keyCount: 1);

            var endpointMonitorId = runtimeEntityType.AddProperty(
                "EndpointMonitorId",
                typeof(Guid),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("EndpointMonitorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<EndpointMonitorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointMonitorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointMonitorId.AddAnnotation("Relational:ColumnName", "endpoint_monitor_id");

            var utcDate = runtimeEntityType.AddProperty(
                "UtcDate",
                typeof(DateOnly),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("UtcDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<UtcDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new DateOnly(1, 1, 1));
            utcDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            utcDate.AddAnnotation("Relational:ColumnName", "utc_date");

            var cancelledCount = runtimeEntityType.AddProperty(
                "CancelledCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("CancelledCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<CancelledCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            cancelledCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            cancelledCount.AddAnnotation("Relational:ColumnName", "cancelled_count");

            var comparabilityIdentity = runtimeEntityType.AddProperty(
                "ComparabilityIdentity",
                typeof(string),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("ComparabilityIdentity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<ComparabilityIdentity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            comparabilityIdentity.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            comparabilityIdentity.AddAnnotation("Relational:ColumnName", "comparability_identity");

            var computedAt = runtimeEntityType.AddProperty(
                "ComputedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("ComputedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<ComputedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            computedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            computedAt.AddAnnotation("Relational:ColumnName", "computed_at");
            computedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var downCount = runtimeEntityType.AddProperty(
                "DownCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DownCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DownCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            downCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            downCount.AddAnnotation("Relational:ColumnName", "down_count");

            var durationCount = runtimeEntityType.AddProperty(
                "DurationCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DurationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DurationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            durationCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            durationCount.AddAnnotation("Relational:ColumnName", "duration_count");

            var durationHistogram = runtimeEntityType.AddProperty(
                "DurationHistogram",
                typeof(long[]),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DurationHistogram", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DurationHistogram>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            var durationHistogramElementType = durationHistogram.SetElementType(typeof(long));
            durationHistogram.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            durationHistogram.AddAnnotation("Relational:ColumnName", "duration_histogram");

            var durationMaximumMs = runtimeEntityType.AddProperty(
                "DurationMaximumMs",
                typeof(int?),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DurationMaximumMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DurationMaximumMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            durationMaximumMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            durationMaximumMs.AddAnnotation("Relational:ColumnName", "duration_maximum_ms");

            var durationMinimumMs = runtimeEntityType.AddProperty(
                "DurationMinimumMs",
                typeof(int?),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DurationMinimumMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DurationMinimumMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            durationMinimumMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            durationMinimumMs.AddAnnotation("Relational:ColumnName", "duration_minimum_ms");

            var durationSumMs = runtimeEntityType.AddProperty(
                "DurationSumMs",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("DurationSumMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<DurationSumMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            durationSumMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            durationSumMs.AddAnnotation("Relational:ColumnName", "duration_sum_ms");

            var eligibleCount = runtimeEntityType.AddProperty(
                "EligibleCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("EligibleCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<EligibleCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            eligibleCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            eligibleCount.AddAnnotation("Relational:ColumnName", "eligible_count");

            var excludedCount = runtimeEntityType.AddProperty(
                "ExcludedCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("ExcludedCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<ExcludedCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            excludedCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            excludedCount.AddAnnotation("Relational:ColumnName", "excluded_count");

            var firstMeasuredAt = runtimeEntityType.AddProperty(
                "FirstMeasuredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("FirstMeasuredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<FirstMeasuredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            firstMeasuredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            firstMeasuredAt.AddAnnotation("Relational:ColumnName", "first_measured_at");
            firstMeasuredAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var healthyCount = runtimeEntityType.AddProperty(
                "HealthyCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("HealthyCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<HealthyCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            healthyCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            healthyCount.AddAnnotation("Relational:ColumnName", "healthy_count");

            var highestSource = runtimeEntityType.AddProperty(
                "HighestSource",
                typeof(string),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("HighestSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<HighestSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 16);
            highestSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            highestSource.AddAnnotation("Relational:ColumnName", "highest_source");

            var histogramVersion = runtimeEntityType.AddProperty(
                "HistogramVersion",
                typeof(int),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("HistogramVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<HistogramVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            histogramVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            histogramVersion.AddAnnotation("Relational:ColumnName", "histogram_version");

            var isComparable = runtimeEntityType.AddProperty(
                "IsComparable",
                typeof(bool),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("IsComparable", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<IsComparable>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isComparable.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isComparable.AddAnnotation("Relational:ColumnName", "is_comparable");

            var lastMeasuredAt = runtimeEntityType.AddProperty(
                "LastMeasuredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("LastMeasuredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<LastMeasuredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            lastMeasuredAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lastMeasuredAt.AddAnnotation("Relational:ColumnName", "last_measured_at");
            lastMeasuredAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var lowestSource = runtimeEntityType.AddProperty(
                "LowestSource",
                typeof(string),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("LowestSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<LowestSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 16);
            lowestSource.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            lowestSource.AddAnnotation("Relational:ColumnName", "lowest_source");

            var maintenanceCount = runtimeEntityType.AddProperty(
                "MaintenanceCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("MaintenanceCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<MaintenanceCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            maintenanceCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maintenanceCount.AddAnnotation("Relational:ColumnName", "maintenance_count");

            var rawDeletionStartedAt = runtimeEntityType.AddProperty(
                "RawDeletionStartedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("RawDeletionStartedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<RawDeletionStartedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            rawDeletionStartedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            rawDeletionStartedAt.AddAnnotation("Relational:ColumnName", "raw_deletion_started_at");
            rawDeletionStartedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var scheduledCount = runtimeEntityType.AddProperty(
                "ScheduledCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("ScheduledCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<ScheduledCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            scheduledCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            scheduledCount.AddAnnotation("Relational:ColumnName", "scheduled_count");

            var totalCount = runtimeEntityType.AddProperty(
                "TotalCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("TotalCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<TotalCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            totalCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            totalCount.AddAnnotation("Relational:ColumnName", "total_count");

            var warningCount = runtimeEntityType.AddProperty(
                "WarningCount",
                typeof(long),
                propertyInfo: typeof(MonitoringDailyAggregate).GetProperty("WarningCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MonitoringDailyAggregate).GetField("<WarningCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            warningCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            warningCount.AddAnnotation("Relational:ColumnName", "warning_count");

            var key = runtimeEntityType.AddKey(
                new[] { endpointMonitorId, utcDate });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_monitoring_daily_aggregate");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_monitoring_daily_aggregate_endpoint_monitor_endpoint_monito~");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "monitoring_daily_aggregate");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
