// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Notifications;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class NotificationDeliveryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Notifications.NotificationDelivery",
                typeof(NotificationDelivery),
                baseEntityType,
                propertyCount: 11,
                navigationCount: 2,
                foreignKeyCount: 1,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(NotificationDelivery).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var attemptCount = runtimeEntityType.AddProperty(
                "AttemptCount",
                typeof(int),
                propertyInfo: typeof(NotificationDelivery).GetProperty("AttemptCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<AttemptCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attemptCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            attemptCount.AddAnnotation("Relational:ColumnName", "attempt_count");

            var channel = runtimeEntityType.AddProperty(
                "Channel",
                typeof(string),
                propertyInfo: typeof(NotificationDelivery).GetProperty("Channel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<Channel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            channel.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            channel.AddAnnotation("Relational:ColumnName", "channel");

            var leaseExpiresAt = runtimeEntityType.AddProperty(
                "LeaseExpiresAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(NotificationDelivery).GetProperty("LeaseExpiresAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<LeaseExpiresAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            leaseExpiresAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            leaseExpiresAt.AddAnnotation("Relational:ColumnName", "lease_expires_at");
            leaseExpiresAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var leaseOwner = runtimeEntityType.AddProperty(
                "LeaseOwner",
                typeof(string),
                propertyInfo: typeof(NotificationDelivery).GetProperty("LeaseOwner", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<LeaseOwner>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            leaseOwner.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            leaseOwner.AddAnnotation("Relational:ColumnName", "lease_owner");

            var nextAttemptAt = runtimeEntityType.AddProperty(
                "NextAttemptAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(NotificationDelivery).GetProperty("NextAttemptAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<NextAttemptAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            nextAttemptAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            nextAttemptAt.AddAnnotation("Relational:ColumnName", "next_attempt_at");
            nextAttemptAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var normalizedRecipient = runtimeEntityType.AddProperty(
                "NormalizedRecipient",
                typeof(string),
                propertyInfo: typeof(NotificationDelivery).GetProperty("NormalizedRecipient", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<NormalizedRecipient>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 320);
            normalizedRecipient.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizedRecipient.AddAnnotation("Relational:ColumnName", "normalized_recipient");

            var notificationEventId = runtimeEntityType.AddProperty(
                "NotificationEventId",
                typeof(Guid),
                propertyInfo: typeof(NotificationDelivery).GetProperty("NotificationEventId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<NotificationEventId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            notificationEventId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            notificationEventId.AddAnnotation("Relational:ColumnName", "notification_event_id");

            var recipientNormalizationVersion = runtimeEntityType.AddProperty(
                "RecipientNormalizationVersion",
                typeof(short),
                propertyInfo: typeof(NotificationDelivery).GetProperty("RecipientNormalizationVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<RecipientNormalizationVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (short)0);
            recipientNormalizationVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            recipientNormalizationVersion.AddAnnotation("Relational:ColumnName", "recipient_normalization_version");

            var sentAt = runtimeEntityType.AddProperty(
                "SentAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(NotificationDelivery).GetProperty("SentAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<SentAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sentAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sentAt.AddAnnotation("Relational:ColumnName", "sent_at");
            sentAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(string),
                propertyInfo: typeof(NotificationDelivery).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            state.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            state.AddAnnotation("Relational:ColumnName", "state");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_notification_delivery");

            var index = runtimeEntityType.AddIndex(
                new[] { normalizedRecipient });
            index.AddAnnotation("Relational:Name", "ix_notification_delivery_normalized_recipient");

            var index0 = runtimeEntityType.AddIndex(
                new[] { state, nextAttemptAt });
            index0.AddAnnotation("Relational:Name", "ix_notification_delivery_state_next_attempt_at");

            var index1 = runtimeEntityType.AddIndex(
                new[] { notificationEventId, channel, normalizedRecipient },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ux_notification_delivery_recipient");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("NotificationEventId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var notificationEvent = declaringEntityType.AddNavigation("NotificationEvent",
                runtimeForeignKey,
                onDependent: true,
                typeof(NotificationEvent),
                propertyInfo: typeof(NotificationDelivery).GetProperty("NotificationEvent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationDelivery).GetField("<NotificationEvent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var deliveries = principalEntityType.AddNavigation("Deliveries",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<NotificationDelivery>),
                propertyInfo: typeof(NotificationEvent).GetProperty("Deliveries", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NotificationEvent).GetField("<Deliveries>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_notification_delivery_notification_event_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "notification_delivery");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
