// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RedirectHopEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.RedirectHop",
                typeof(RedirectHop),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(RedirectHop).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var hopNumber = runtimeEntityType.AddProperty(
                "HopNumber",
                typeof(int),
                propertyInfo: typeof(RedirectHop).GetProperty("HopNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<HopNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            hopNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            hopNumber.AddAnnotation("Relational:ColumnName", "hop_number");

            var httpStatus = runtimeEntityType.AddProperty(
                "HttpStatus",
                typeof(int),
                propertyInfo: typeof(RedirectHop).GetProperty("HttpStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<HttpStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            httpStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            httpStatus.AddAnnotation("Relational:ColumnName", "http_status");

            var isLoop = runtimeEntityType.AddProperty(
                "IsLoop",
                typeof(bool),
                propertyInfo: typeof(RedirectHop).GetProperty("IsLoop", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<IsLoop>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isLoop.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isLoop.AddAnnotation("Relational:ColumnName", "is_loop");

            var logicalCheckId = runtimeEntityType.AddProperty(
                "LogicalCheckId",
                typeof(Guid),
                propertyInfo: typeof(RedirectHop).GetProperty("LogicalCheckId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<LogicalCheckId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            logicalCheckId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            logicalCheckId.AddAnnotation("Relational:ColumnName", "logical_check_id");

            var normalizedFromUrl = runtimeEntityType.AddProperty(
                "NormalizedFromUrl",
                typeof(string),
                propertyInfo: typeof(RedirectHop).GetProperty("NormalizedFromUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<NormalizedFromUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2048);
            normalizedFromUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizedFromUrl.AddAnnotation("Relational:ColumnName", "normalized_from_url");

            var normalizedToUrl = runtimeEntityType.AddProperty(
                "NormalizedToUrl",
                typeof(string),
                propertyInfo: typeof(RedirectHop).GetProperty("NormalizedToUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<NormalizedToUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2048);
            normalizedToUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizedToUrl.AddAnnotation("Relational:ColumnName", "normalized_to_url");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_redirect_hop");

            var index = runtimeEntityType.AddIndex(
                new[] { logicalCheckId, hopNumber },
                unique: true);
            index.AddAnnotation("Relational:Name", "ix_redirect_hop_logical_check_id_hop_number");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("LogicalCheckId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("LogicalCheckId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var result = declaringEntityType.AddNavigation("Result",
                runtimeForeignKey,
                onDependent: true,
                typeof(CheckResult),
                propertyInfo: typeof(RedirectHop).GetProperty("Result", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RedirectHop).GetField("<Result>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var redirectHops = principalEntityType.AddNavigation("RedirectHops",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<RedirectHop>),
                propertyInfo: typeof(CheckResult).GetProperty("RedirectHops", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CheckResult).GetField("<RedirectHops>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_redirect_hop_check_result_logical_check_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "redirect_hop");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
