// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Seo;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RobotsSnapshotEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Seo.RobotsSnapshot",
                typeof(RobotsSnapshot),
                baseEntityType,
                propertyCount: 18,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var origin = runtimeEntityType.AddProperty(
                "Origin",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Origin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Origin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 300);
            origin.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            origin.AddAnnotation("Relational:ColumnName", "origin");

            var checkedSitemapUrl = runtimeEntityType.AddProperty(
                "CheckedSitemapUrl",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("CheckedSitemapUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<CheckedSitemapUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            checkedSitemapUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            checkedSitemapUrl.AddAnnotation("Relational:ColumnName", "checked_sitemap_url");

            var configuredSitemapUrl = runtimeEntityType.AddProperty(
                "ConfiguredSitemapUrl",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("ConfiguredSitemapUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<ConfiguredSitemapUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            configuredSitemapUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            configuredSitemapUrl.AddAnnotation("Relational:ColumnName", "configured_sitemap_url");

            var content = runtimeEntityType.AddProperty(
                "Content",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Content", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Content>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 524288);
            content.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            content.AddAnnotation("Relational:ColumnName", "content");

            var exceptionApprovedAt = runtimeEntityType.AddProperty(
                "ExceptionApprovedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("ExceptionApprovedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<ExceptionApprovedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            exceptionApprovedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            exceptionApprovedAt.AddAnnotation("Relational:ColumnName", "exception_approved_at");
            exceptionApprovedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var exceptionApprovedByUserId = runtimeEntityType.AddProperty(
                "ExceptionApprovedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("ExceptionApprovedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<ExceptionApprovedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            exceptionApprovedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            exceptionApprovedByUserId.AddAnnotation("Relational:ColumnName", "exception_approved_by_user_id");

            var exceptionReason = runtimeEntityType.AddProperty(
                "ExceptionReason",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("ExceptionReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<ExceptionReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            exceptionReason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            exceptionReason.AddAnnotation("Relational:ColumnName", "exception_reason");

            var expiresAt = runtimeEntityType.AddProperty(
                "ExpiresAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("ExpiresAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<ExpiresAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            expiresAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            expiresAt.AddAnnotation("Relational:ColumnName", "expires_at");
            expiresAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var fetchedAt = runtimeEntityType.AddProperty(
                "FetchedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("FetchedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<FetchedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            fetchedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            fetchedAt.AddAnnotation("Relational:ColumnName", "fetched_at");
            fetchedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var host = runtimeEntityType.AddProperty(
                "Host",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Host", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Host>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 253);
            host.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            host.AddAnnotation("Relational:ColumnName", "host");

            var httpStatus = runtimeEntityType.AddProperty(
                "HttpStatus",
                typeof(int?),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("HttpStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<HttpStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            httpStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            httpStatus.AddAnnotation("Relational:ColumnName", "http_status");

            var port = runtimeEntityType.AddProperty(
                "Port",
                typeof(int),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Port", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Port>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            port.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            port.AddAnnotation("Relational:ColumnName", "port");

            var sitemapAvailable = runtimeEntityType.AddProperty(
                "SitemapAvailable",
                typeof(bool),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("SitemapAvailable", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<SitemapAvailable>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            sitemapAvailable.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sitemapAvailable.AddAnnotation("Relational:ColumnName", "sitemap_available");

            var sitemapHttpStatus = runtimeEntityType.AddProperty(
                "SitemapHttpStatus",
                typeof(int?),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("SitemapHttpStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<SitemapHttpStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sitemapHttpStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sitemapHttpStatus.AddAnnotation("Relational:ColumnName", "sitemap_http_status");

            var sitemapRequired = runtimeEntityType.AddProperty(
                "SitemapRequired",
                typeof(bool),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("SitemapRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<SitemapRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            sitemapRequired.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            sitemapRequired.AddAnnotation("Relational:ColumnName", "sitemap_required");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:ColumnName", "status");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");
            updatedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(RobotsSnapshot).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RobotsSnapshot).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            version.AddAnnotation("Relational:ColumnName", "version");

            var key = runtimeEntityType.AddKey(
                new[] { origin });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_robots_snapshot");

            var index = runtimeEntityType.AddIndex(
                new[] { exceptionApprovedByUserId });
            index.AddAnnotation("Relational:Name", "ix_robots_snapshot_exception_approved_by_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { expiresAt });
            index0.AddAnnotation("Relational:Name", "ix_robots_snapshot_expires_at");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ExceptionApprovedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_robots_snapshot_app_user_exception_approved_by_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "robots_snapshot");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
