// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;
using WebHealth.Infrastructure.Registry;
using WebHealth.Infrastructure.Seo;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SeoObservationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Seo.SeoObservation",
                typeof(SeoObservation),
                baseEntityType,
                propertyCount: 22,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var logicalCheckId = runtimeEntityType.AddProperty(
                "LogicalCheckId",
                typeof(Guid),
                propertyInfo: typeof(SeoObservation).GetProperty("LogicalCheckId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<LogicalCheckId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            logicalCheckId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            logicalCheckId.AddAnnotation("Relational:ColumnName", "logical_check_id");

            var applicability = runtimeEntityType.AddProperty(
                "Applicability",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("Applicability", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<Applicability>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            applicability.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            applicability.AddAnnotation("Relational:ColumnName", "applicability");

            var canonicalAbsoluteUrl = runtimeEntityType.AddProperty(
                "CanonicalAbsoluteUrl",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("CanonicalAbsoluteUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<CanonicalAbsoluteUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            canonicalAbsoluteUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            canonicalAbsoluteUrl.AddAnnotation("Relational:ColumnName", "canonical_absolute_url");

            var canonicalCount = runtimeEntityType.AddProperty(
                "CanonicalCount",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("CanonicalCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<CanonicalCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            canonicalCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            canonicalCount.AddAnnotation("Relational:ColumnName", "canonical_count");

            var canonicalHref = runtimeEntityType.AddProperty(
                "CanonicalHref",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("CanonicalHref", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<CanonicalHref>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            canonicalHref.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            canonicalHref.AddAnnotation("Relational:ColumnName", "canonical_href");

            var canonicalLength = runtimeEntityType.AddProperty(
                "CanonicalLength",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("CanonicalLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<CanonicalLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            canonicalLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            canonicalLength.AddAnnotation("Relational:ColumnName", "canonical_length");

            var documentTruncated = runtimeEntityType.AddProperty(
                "DocumentTruncated",
                typeof(bool),
                propertyInfo: typeof(SeoObservation).GetProperty("DocumentTruncated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<DocumentTruncated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            documentTruncated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            documentTruncated.AddAnnotation("Relational:ColumnName", "document_truncated");

            var endpointMonitorId = runtimeEntityType.AddProperty(
                "EndpointMonitorId",
                typeof(Guid),
                propertyInfo: typeof(SeoObservation).GetProperty("EndpointMonitorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<EndpointMonitorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointMonitorId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointMonitorId.AddAnnotation("Relational:ColumnName", "endpoint_monitor_id");

            var metaDescription = runtimeEntityType.AddProperty(
                "MetaDescription",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("MetaDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<MetaDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1024);
            metaDescription.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            metaDescription.AddAnnotation("Relational:ColumnName", "meta_description");

            var metaDescriptionCount = runtimeEntityType.AddProperty(
                "MetaDescriptionCount",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("MetaDescriptionCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<MetaDescriptionCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            metaDescriptionCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            metaDescriptionCount.AddAnnotation("Relational:ColumnName", "meta_description_count");

            var metaDescriptionLength = runtimeEntityType.AddProperty(
                "MetaDescriptionLength",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("MetaDescriptionLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<MetaDescriptionLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            metaDescriptionLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            metaDescriptionLength.AddAnnotation("Relational:ColumnName", "meta_description_length");

            var notApplicableReason = runtimeEntityType.AddProperty(
                "NotApplicableReason",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("NotApplicableReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<NotApplicableReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 30);
            notApplicableReason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            notApplicableReason.AddAnnotation("Relational:ColumnName", "not_applicable_reason");

            var observedAt = runtimeEntityType.AddProperty(
                "ObservedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SeoObservation).GetProperty("ObservedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<ObservedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            observedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            observedAt.AddAnnotation("Relational:ColumnName", "observed_at");
            observedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var policyDescriptionRequired = runtimeEntityType.AddProperty(
                "PolicyDescriptionRequired",
                typeof(bool),
                propertyInfo: typeof(SeoObservation).GetProperty("PolicyDescriptionRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<PolicyDescriptionRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            policyDescriptionRequired.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            policyDescriptionRequired.AddAnnotation("Relational:ColumnName", "policy_description_required");

            var policyExpectedHost = runtimeEntityType.AddProperty(
                "PolicyExpectedHost",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("PolicyExpectedHost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<PolicyExpectedHost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 253);
            policyExpectedHost.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            policyExpectedHost.AddAnnotation("Relational:ColumnName", "policy_expected_host");

            var policyIndexingExpectation = runtimeEntityType.AddProperty(
                "PolicyIndexingExpectation",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("PolicyIndexingExpectation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<PolicyIndexingExpectation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 20);
            policyIndexingExpectation.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            policyIndexingExpectation.AddAnnotation("Relational:ColumnName", "policy_indexing_expectation");

            var robotsMeta = runtimeEntityType.AddProperty(
                "RobotsMeta",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("RobotsMeta", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<RobotsMeta>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            robotsMeta.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            robotsMeta.AddAnnotation("Relational:ColumnName", "robots_meta");

            var robotsMetaCount = runtimeEntityType.AddProperty(
                "RobotsMetaCount",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("RobotsMetaCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<RobotsMetaCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            robotsMetaCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            robotsMetaCount.AddAnnotation("Relational:ColumnName", "robots_meta_count");

            var robotsMetaLength = runtimeEntityType.AddProperty(
                "RobotsMetaLength",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("RobotsMetaLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<RobotsMetaLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            robotsMetaLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            robotsMetaLength.AddAnnotation("Relational:ColumnName", "robots_meta_length");

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(SeoObservation).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 512);
            title.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            title.AddAnnotation("Relational:ColumnName", "title");

            var titleCount = runtimeEntityType.AddProperty(
                "TitleCount",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("TitleCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<TitleCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            titleCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            titleCount.AddAnnotation("Relational:ColumnName", "title_count");

            var titleLength = runtimeEntityType.AddProperty(
                "TitleLength",
                typeof(int),
                propertyInfo: typeof(SeoObservation).GetProperty("TitleLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<TitleLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            titleLength.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            titleLength.AddAnnotation("Relational:ColumnName", "title_length");

            var key = runtimeEntityType.AddKey(
                new[] { logicalCheckId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_seo_observation");

            var index = runtimeEntityType.AddIndex(
                new[] { endpointMonitorId, observedAt });
            index.AddAnnotation("Relational:Name", "ix_seo_observation_endpoint_monitor_id_observed_at");

            var index0 = runtimeEntityType.AddIndex(
                new[] { logicalCheckId, endpointMonitorId },
                unique: true);
            index0.AddAnnotation("Relational:Name", "ix_seo_observation_logical_check_id_endpoint_monitor_id");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var endpointMonitor = declaringEntityType.AddNavigation("EndpointMonitor",
                runtimeForeignKey,
                onDependent: true,
                typeof(EndpointMonitor),
                propertyInfo: typeof(SeoObservation).GetProperty("EndpointMonitor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<EndpointMonitor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_seo_observation_endpoint_monitor_endpoint_monitor_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("LogicalCheckId"), declaringEntityType.FindProperty("EndpointMonitorId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id"), principalEntityType.FindProperty("EndpointMonitorId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                unique: true,
                required: true);

            var logicalCheck = declaringEntityType.AddNavigation("LogicalCheck",
                runtimeForeignKey,
                onDependent: true,
                typeof(LogicalCheck),
                propertyInfo: typeof(SeoObservation).GetProperty("LogicalCheck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SeoObservation).GetField("<LogicalCheck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_seo_observation_logical_check_logical_check_id_endpoint_mon~");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "seo_observation");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
