// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Monitoring;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TargetAuthorizationEvidenceEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Monitoring.TargetAuthorizationEvidence",
                typeof(TargetAuthorizationEvidence),
                baseEntityType,
                propertyCount: 13,
                foreignKeyCount: 3,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var authorizationKind = runtimeEntityType.AddProperty(
                "AuthorizationKind",
                typeof(string),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("AuthorizationKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<AuthorizationKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            authorizationKind.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            authorizationKind.AddAnnotation("Relational:ColumnName", "authorization_kind");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var createdByUserId = runtimeEntityType.AddProperty(
                "CreatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("CreatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<CreatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            createdByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdByUserId.AddAnnotation("Relational:ColumnName", "created_by_user_id");

            var effectiveFrom = runtimeEntityType.AddProperty(
                "EffectiveFrom",
                typeof(DateTimeOffset),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("EffectiveFrom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<EffectiveFrom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            effectiveFrom.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            effectiveFrom.AddAnnotation("Relational:ColumnName", "effective_from");
            effectiveFrom.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var endpointId = runtimeEntityType.AddProperty(
                "EndpointId",
                typeof(Guid),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("EndpointId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<EndpointId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            endpointId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            endpointId.AddAnnotation("Relational:ColumnName", "endpoint_id");

            var evidenceReference = runtimeEntityType.AddProperty(
                "EvidenceReference",
                typeof(string),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("EvidenceReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<EvidenceReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            evidenceReference.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            evidenceReference.AddAnnotation("Relational:ColumnName", "evidence_reference");

            var expiresAt = runtimeEntityType.AddProperty(
                "ExpiresAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("ExpiresAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<ExpiresAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expiresAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            expiresAt.AddAnnotation("Relational:ColumnName", "expires_at");
            expiresAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var normalizedHost = runtimeEntityType.AddProperty(
                "NormalizedHost",
                typeof(string),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("NormalizedHost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<NormalizedHost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 253);
            normalizedHost.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizedHost.AddAnnotation("Relational:ColumnName", "normalized_host");

            var port = runtimeEntityType.AddProperty(
                "Port",
                typeof(int),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("Port", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<Port>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            port.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            port.AddAnnotation("Relational:ColumnName", "port");

            var revocationReason = runtimeEntityType.AddProperty(
                "RevocationReason",
                typeof(string),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("RevocationReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<RevocationReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            revocationReason.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            revocationReason.AddAnnotation("Relational:ColumnName", "revocation_reason");

            var revokedAt = runtimeEntityType.AddProperty(
                "RevokedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("RevokedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<RevokedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            revokedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            revokedAt.AddAnnotation("Relational:ColumnName", "revoked_at");
            revokedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var revokedByUserId = runtimeEntityType.AddProperty(
                "RevokedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(TargetAuthorizationEvidence).GetProperty("RevokedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TargetAuthorizationEvidence).GetField("<RevokedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            revokedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            revokedByUserId.AddAnnotation("Relational:ColumnName", "revoked_by_user_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_target_authorization_evidence");

            var index = runtimeEntityType.AddIndex(
                new[] { createdByUserId });
            index.AddAnnotation("Relational:Name", "ix_target_authorization_evidence_created_by_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { revokedByUserId });
            index0.AddAnnotation("Relational:Name", "ix_target_authorization_evidence_revoked_by_user_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { endpointId, normalizedHost, port });
            index1.AddAnnotation("Relational:Name", "ix_target_authorization_evidence_endpoint_id_normalized_host_p~");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CreatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_target_authorization_evidence_app_user_created_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EndpointId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_target_authorization_evidence_endpoint_endpoint_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RevokedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_target_authorization_evidence_app_user_revoked_by_user_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "target_authorization_evidence");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
