// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHealth.Infrastructure.Registry;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebHealth.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class WebsiteEnvironmentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebHealth.Infrastructure.Registry.WebsiteEnvironment",
                typeof(WebsiteEnvironment),
                baseEntityType,
                propertyCount: 16,
                navigationCount: 2,
                foreignKeyCount: 4,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var baseUrl = runtimeEntityType.AddProperty(
                "BaseUrl",
                typeof(string),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("BaseUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<BaseUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            baseUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            baseUrl.AddAnnotation("Relational:ColumnName", "base_url");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");
            createdAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var createdByUserId = runtimeEntityType.AddProperty(
                "CreatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("CreatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<CreatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            createdByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdByUserId.AddAnnotation("Relational:ColumnName", "created_by_user_id");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");
            deletedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var deletedByUserId = runtimeEntityType.AddProperty(
                "DeletedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("DeletedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<DeletedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            deletedByUserId.AddAnnotation("Relational:ColumnName", "deleted_by_user_id");

            var environmentType = runtimeEntityType.AddProperty(
                "EnvironmentType",
                typeof(string),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("EnvironmentType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<EnvironmentType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            environmentType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            environmentType.AddAnnotation("Relational:ColumnName", "environment_type");

            var isActive = runtimeEntityType.AddProperty(
                "IsActive",
                typeof(bool),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isActive.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isActive.AddAnnotation("Relational:ColumnName", "is_active");

            var isProduction = runtimeEntityType.AddProperty(
                "IsProduction",
                typeof(bool),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("IsProduction", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<IsProduction>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isProduction.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isProduction.AddAnnotation("Relational:ColumnName", "is_production");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            name.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            name.AddAnnotation("Relational:ColumnName", "name");

            var normalizationVersion = runtimeEntityType.AddProperty(
                "NormalizationVersion",
                typeof(short),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("NormalizationVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<NormalizationVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: (short)0);
            normalizationVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizationVersion.AddAnnotation("Relational:ColumnName", "normalization_version");
            normalizationVersion.AddAnnotation("Relational:DefaultValue", (short)1);

            var normalizedName = runtimeEntityType.AddProperty(
                "NormalizedName",
                typeof(string),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("NormalizedName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<NormalizedName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            normalizedName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            normalizedName.AddAnnotation("Relational:ColumnName", "normalized_name");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");
            updatedAt.AddAnnotation("Relational:ColumnType", "timestamp with time zone");

            var updatedByUserId = runtimeEntityType.AddProperty(
                "UpdatedByUserId",
                typeof(Guid),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("UpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<UpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            updatedByUserId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedByUserId.AddAnnotation("Relational:ColumnName", "updated_by_user_id");

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            version.AddAnnotation("Relational:ColumnName", "version");

            var websiteId = runtimeEntityType.AddProperty(
                "WebsiteId",
                typeof(Guid),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("WebsiteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<WebsiteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            websiteId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            websiteId.AddAnnotation("Relational:ColumnName", "website_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_environment");

            var index = runtimeEntityType.AddIndex(
                new[] { createdByUserId });
            index.AddAnnotation("Relational:Name", "ix_environment_created_by_user_id");

            var index0 = runtimeEntityType.AddIndex(
                new[] { deletedByUserId });
            index0.AddAnnotation("Relational:Name", "ix_environment_deleted_by_user_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { updatedByUserId });
            index1.AddAnnotation("Relational:Name", "ix_environment_updated_by_user_id");

            var index2 = runtimeEntityType.AddIndex(
                new[] { websiteId, deletedAt, isActive });
            index2.AddAnnotation("Relational:Name", "ix_environment_website_id_deleted_at_is_active");

            var index3 = runtimeEntityType.AddIndex(
                new[] { websiteId, normalizedName, normalizationVersion },
                unique: true);
            index3.AddAnnotation("Relational:Filter", "deleted_at IS NULL");
            index3.AddAnnotation("Relational:Name", "ix_environment_website_id_normalized_name_normalization_version");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CreatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_environment_app_user_created_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DeletedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_environment_app_user_deleted_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedByUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_environment_app_user_updated_by_user_id");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("WebsiteId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var website = declaringEntityType.AddNavigation("Website",
                runtimeForeignKey,
                onDependent: true,
                typeof(Website),
                propertyInfo: typeof(WebsiteEnvironment).GetProperty("Website", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WebsiteEnvironment).GetField("<Website>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var environments = principalEntityType.AddNavigation("Environments",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<WebsiteEnvironment>),
                propertyInfo: typeof(Website).GetProperty("Environments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Website).GetField("<Environments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_environment_website_website_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "web_health");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "environment");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
