<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>web-health-project-development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebHealth.Application\WebHealth.Application.csproj" />
    <ProjectReference Include="..\WebHealth.Infrastructure\WebHealth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
