<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebHealth.Application\WebHealth.Application.csproj" />
    <ProjectReference Include="..\WebHealth.Domain\WebHealth.Domain.csproj" />
  </ItemGroup>
</Project>
